export const indiceHtml = ["Introducción",
                            "Estructura general",
                            "Sintaxis básica",
                            "Anatomía de un documento", 
                            "Más sobre head", 
                            "Más sobre body",
                            "Semántica general", 
                            "Hipervínculos", 
                            "Imágenes",
                            "Audio y video", 
                            "Tablas", 
                            "Formularios",
                            "Botones", 
                            "Debug"];

export const indiceCss =   ["Introducción",
                            "Más sobre selectores",
                            "Box model",
                            "Conflictos",
                            "Valores y unidades",
                            "Dimensionando elementos",
                            "Fondos y bordes",
                            "Contenido desbordado",
                            "Imágenes, media y formularios",
                            "Tablas",
                            "Debug",
                            "Estilos para textos",
                            "Estilando listas",
                            "Estilando links",
                            "Web fonts",
                            "Layouts",
                            "Floats",
                            "Positioning",
                            "Flex-box",
                            "Grid",
                            "Responsive design",
                            "Media query",];

export const indiceJavaScript = ["Introducción",
                                "Un primer acercamiento a la programación en si",
                                "Variables",
                                "Operaciones y comparadores básicos",
                                "Strings",
                                "Arrays",
                                "Condicionales",
                                "Loops",
                                "Funciones",
                                "Eventos",
                                "Objetos en JavaScript",
                                "DOM scripting",
                                "Network requests",
                                "JSON",
                                "Debug"];